[versions]
agp = "9.0.0"
jspecify = "1.0.0"

[libraries]
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }